[package]
name = "NES"
version = "0.1.0"
authors = ["Samuel W. <sam.wang21950@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35.2"
rand = "=0.8.5"